# Generated by Django 3.2.4 on 2021-06-22 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('patronym', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, upload_to='graduates/', verbose_name='Фотография')),
                ('graduated', models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2021)], verbose_name='Год выпуска')),
                ('faculty', models.CharField(max_length=200, verbose_name='Факультет')),
                ('career', models.TextField(verbose_name='Карьера')),
                ('contacts', models.CharField(max_length=300, verbose_name='Контакты')),
            ],
        ),
    ]
