# Generated by Django 3.2.4 on 2021-06-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='contacts',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='patronym',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
    ]
