# Generated by Django 3.2.4 on 2021-06-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0003_graduate_cafedra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Контакты'),
        ),
    ]
