# Generated by Django 3.2.4 on 2021-06-23 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0004_alter_graduate_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='graduated',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2021)], verbose_name='Год выпуска'),
        ),
    ]
